FROM java:8 


EXPOSE 8080

ADD /target/teste-geofusion-jp-0.0.1-SNAPSHOT.jar teste-geofusion-jp-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "teste-geofusion-jp-0.0.1-SNAPSHOT.jar"]

RUN echo "TESTE GEOFUSION"



//https://www.javainuse.com/devOps/docker/docker-mysql
